---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
# nginx-ingress for local cluster env
- path: cluster-setup/nginx-ingress
  contents:
  - path: .
    git:
      url: https://github.com/kubernetes/ingress-nginx.git
      ref: controller-v1.8.1
      depth: 1
    includePaths:
    - deploy/static/provider/kind/deploy.yaml
- path: cluster-setup/kapp-controller
  contents:
  - path: .
    githubRelease:
      slug: carvel-dev/kapp-controller
      tag: v0.47.0
      assetNames: ["release.yml"]
