apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: carvel-demo.garnier.wf.1.0.0
spec:
  refName: carvel-demo.garnier.wf
  releasedAt: "2023-09-08T07:54:35Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: index.docker.io/dgarnier963/carvel-demo-package@sha256:5456f91d4cd652305b19e381e609f79919f98da8eb8acfef2614466e9b78371f
      template:
      - ytt:
          paths:
          - application
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        apps:
          default: []
          items:
            additionalProperties: false
            properties:
              html:
                default: ""
                type: string
              name:
                default: ""
                type: string
              public:
                default: true
                type: boolean
            type: object
          type: array
      type: object
  version: 1.0.0
