apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: carvel-demo.garnier.wf.0.0.0
spec:
  refName: carvel-demo.garnier.wf
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - app
          - app-private
          - infra
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: carvel-demo.garnier.wf
spec:
  displayName: carvel-demo
  longDescription: carvel-demo.garnier.wf
  shortDescription: carvel-demo.garnier.wf

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: carvel-demo
spec:
  packageRef:
    refName: carvel-demo.garnier.wf
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: carvel-demo-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
