apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: carvel-demo.garnier.wf
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - app
              - app-private
              - infra
          - kbld: {}
      export:
      - imgpkgBundle:
          image: docker.io/dgarnier963/carvel-demo
          useKbldImagesLock: true
        includePaths:
        - app
        - app-private
        - infra
