---
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: Bundle
metadata:
  name: carvel-demo
authors:
- name: Daniel Garnier-Moiroux
  email: git@garnier.wf
websites:
- url: https://github.com/Kehrlann/carvel-demo
