---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: full-app
  namespace: default

spec:
  serviceAccountName: kapp-controller-sa
  syncPeriod: 1m
  fetch:
    # Watch out: pulling the bundle may hit DockerHub rate limits
    #- imgpkgBundle:
    #    image: docker.io/dgarnier963/carvel-demo:v1.0.0
    #  path: bundle

    - git:
        url: https://github.com/Kehrlann/carvel-demo.git
        ref: demo
        subPath: demo/application
      path: bundle

    - git:
        url: https://github.com/Kehrlann/carvel-demo.git
        ref: gitops
      path: git

  template:
    # use ytt to template configuration
    - ytt:
        paths:
          - bundle/app/
          - bundle/app-private/
          - bundle/infra/
        valuesFrom:
          #- secretRef:
          #    name: app-configuration
          - path: git/my-custom-values.yml


    # use kbld to resolve image references to use digests
    - kbld:
        paths:
        - bundle/.imgpkg/images.yml
        - "-"

  deploy:
    - kapp: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: app-configuration
  namespace: default
stringData:
  values.yml: |
    apps:
      - name: "fraises"
        html: |
          <body>
            <h1>Strawberries playing music together</h1>
            <p>They're jamming!</p>
          </body>
        public: true
      - name: "bananes"
        html: |
          <body>
            <h1>This is Bananas!</h1>
            <p>Seriously, this is bananas.</p>
          </body>
        public: false
      - name: "pommes"
        html: |
          <body>
            <h1>An apple a day keeps the doctor away</h1>
            <p>But only if you aim correctly and throw it really hard.</p>
          </body>
        public: false
